version: '3'

services:
  app:
    image: docker.io/pixielark/powerpanel-business:local-latest
    #build: .
    ports:
      - 3052:3052
    privileged: true
    restart: unless-stopped
    volumes:
      - app_data:/usr/local/ppbe/db_local/
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone

volumes:
  app_data:
    driver: local
